.TH SET 3
.UC 4
.SH NAME
set \- procedures for setting parameters (from strings) and for 
printing their values.

.SH SYNOPSIS
.nf
.PP
.B "Void SetNoisyInt(parm,valueS,file)"
.B "int *parm;"
.B "char *valueS;"
.B "FILE *file;"
.PP
.B "Void SetNoisyBool(parm,valueS,file)"
.B "bool *parm;"
.B "char *valueS;"
.B "FILE *file;"
.PP
.B "Void SetNoisyDI(parm,valueS,file)"
.B "DoubleInt *parm;"
.B "char *valueS;"
.B "FILE *file;"

.SH DESCRIPTION
These procedures interpet a string and set a parameter accordingly.  Error
messages are printed if the string doesn't make sense, and in any event
the final parameter value is printed.  If \fIvalueS\fR is \fBNULL\fR, 
the parameter
value is not changed.  If \fIfile\fR is \fBNULL\fR the result is printed
with \fITxPrintf\fR, Magic's standard print function, otherwise it is printed
on  the specified file.

.SH SEE ALSO
magicutils\|(3)
