.TH NET2IR 1 
.SH NAME
net2ir \- produce :iroute commands to route a netlist composed of two-point nets
.SH SYNOPSIS
.B net2ir
.I feedfile
.I netfile
.SH DESCRIPTION
\fINet2ir\fR is used to produce commands for the Magic interactive hint
router to route the collection of two-point nets specified in the
\fInet\fR\|(5) file \fInetfile\fR, in the order in which they
appear in the file.
The label locations come from \fIfeedfile\fR,
which should consist of a series of \fBbox\fR and
\fBfeedback add\fR Magic commands, such as produced
by the \fBfind\fR command (in a Magic netlist window).
The text associated with each feedback command must
be of the form \fIlayer\fB;\fIlabel\fR, where \fIlayer\fR
is the Magic layer on which \fIlabel\fR lies.
.PP
The output of \fInet2ir\fR is a sequence of \fB:iroute route\fR
commands, one for each net in the netlist file.

.SH "SEE ALSO"
magic\|(1), net\|(5)

.SH AUTHOR
Walter Scott
