.TH SHOW 3
.UC 4
.SH NAME
show \- procedure for displaying rects as feedback, for debugging.
printing their values.

.SH SYNOPSIS
.nf
.PP
.B "Void ShowRect(def, r, style)"
.B "CellDef *def;"
.B "Rect *r;"
.B "int style;"

.SH DESCRIPTION
Highlights the specified area in the specified cell and the specified style.
See the Magic \fIgarouter\fR module for example uses.

.SH SEE ALSO
magicutils\|(3)
